reddit.com##.unvoted.entry:has-text(/[^\w]+(three|3)[ ]*sea[ ]*shell(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+trump(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+Poem_for_your_sprog[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+\(.* ͡.* ͡.*\)[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+Kardashian(s)*[^\w]/i)
