reddit.com##.unvoted.entry:has-text(/[^\w]+(three|3)[ ]*sea[ ]*shell(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+trump(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+Poem_for_your_sprog[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+\(.* ͡.* ͡.*\)[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+Kardashian(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+inb4(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+r[ae]*l[ae]*v[ae]*nt[^\w]*user[ ]*name(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+And[ ]*my[ ]*Axe(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+mem(e|ing)(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+sex(y)*[ ]*time(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+remind[ ]*me[!]*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]I[ ]*also[ ]*choose[ ]*this[ ]*[^ ]+[ ]*dead[ ]*(wife|husband|partner|girlfriend|boyfriend|bf|gf)[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]Sex[ ]*with[ ]*this[ ]*[^ ]+[ ]*(wife|husband|partner|girlfriend|boyfriend|bf|gf)[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]I[ ]*understood[ ]*that[ ]*reference[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]senpai[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]Jaime[ ]*pull[ ]*it[ ]*up[^\w]/i)
reddit.com##.unvoted.entry:has-text(/u\/[^ ]+/)
reddit.com##.unvoted.entry:has-text(/[^\w]up(d|t)oot[s]*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]pioneer[s]* used to ride [\w]+ bab(ies|ys) [\w]+ mile[s]*[^\w]/i)
