reddit.com##.unvoted.entry:has-text(/[^\w]+(three|3)[ ]*sea[ ]*shell(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+trump(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+Poem_for_your_sprog[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+\(.* ͡.* ͡.*\)[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+Kardashian(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+inb4(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+r[ae]*l[ae]*v[ae]*nt[^\w]*user[ ]*name(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+And[ ]*my[ ]*Axe(s)*[^\w]/i)
reddit.com##.unvoted.entry:has-text(/[^\w]+mem(e|ing)(s)*[^\w]/i)
